override SOURCEROOT	= ../..
CXXFLAGS   += -DSOLUTION
PROGRAMS 		= tint
OWN_LIBS 		= Graphics Geometry CGLA Components Common
LIBS			= ${GLUTLIBS} ${GLLIBS} ${WIN_SYS_LIBS} -lm

include ${SOURCEROOT}/makefiles/application.mk
